apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: security-feed-web-data
  labels:
    app: security-feed-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
