apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: security-feed-api-data
  labels:
    app: security-feed-api
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "longhorn-rwx"
  resources:
    requests:
      storage: 1Gi
